More verbose logs when running `airflow check_migrations` (#15662)
Currently it just shows "TimeoutError: There are still unapplied migrations after 60 seconds. " which is not that helpful.

This commit adds more info to show the difference in migrations in DB and source code running `check_migrations`:

Now:

```
TimeoutError: There are still unapplied migrations after 60 seconds. Migration Head(s) in DB: {'e165e7455d70'} | Migration Head(s) in Source Code: {'a13f7613ad25'}
```

closes https://github.com/apache/airflow/issues/15650