Fix statsd metrics not sending when using daemon mode (#14454)
It seems that the daemonContext will close the socket of statsd.

```
    return self.statsd.incr(stat, count, rate)
  File "/usr/local/lib/python3.8/site-packages/statsd/client/base.py", line 35, in incr
    self._send_stat(stat, '%s|c' % count, rate)
  File "/usr/local/lib/python3.8/site-packages/statsd/client/base.py", line 59, in _send_stat
    self._after(self._prepare(stat, value, rate))
  File "/usr/local/lib/python3.8/site-packages/statsd/client/base.py", line 74, in _after
    self._send(data)
  File "/opt/airflow/airflow/stats.py", line 40, in _send
    self._sock.sendto(data.encode('ascii'), self._addr)
OSError: [Errno 9] Bad file descriptor
```

(cherry picked from commit 0aa597e2ffd71d3587f629c0a1cb3d904e07b6e6)