REST API: Fix wrong plugin schema (#34858)
* REST API: Fix wrong plugin schema

We serialize some plugin's fields as dictionaries leading to errors
when accessing the `/plugins` endpoint.

Here's the error:
ValueError: dictionary update sequence element #0 has length 1; 2 is required

The fields are lists of strings and this PR addresses it.

* fixup! REST API: Fix wrong plugin schema

* Add test at the endpoint

* fixup! Add test at the endpoint