[AIRFLOW-3761] Fix `DROP TABLE user` migration for upgrades. (#4840)
If you are upgrading an old install you will likely have rows in the
user and known_event tables. We dropped the KnownEvent without a
migration to remove it (on purpose) in [AIRFLOW-3468] (#4421) but this
means if we have any rows in there we won't be able to drop the USER
table:

> sqlalchemy.exc.InternalError: (psycopg2.InternalError) cannot drop table users because other objects depend on it
> DETAIL:  constraint known_event_user_id_fkey on table known_event depends on table users

So we need to drop that FK constraint first (if the table exists, which
it won't on a fresh install, as the create migration has been deleted.)