Fix MyPy issues in ``airflow/macros`` (#20613)
* Fix MyPy issues in ``airflow/macros``

**Before**:
```
root@57b2ac1779ad:/opt/airflow# mypy --namespace-packages airflow/macros
airflow/macros/__init__.py:83: error: Argument 1 to "diff_for_humans" of "DateTime" has incompatible type "Optional[datetime]"; expected "Optional[DateTime]"
        return pendulum.instance(dt).diff_for_humans(since)
                                                     ^
Found 1 error in 1 file (checked 2 source files)
```

**After**:
```
root@57b2ac1779ad:/opt/airflow# mypy --namespace-packages airflow/macros
Success: no issues found in 2 source files
```

* Update __init__.py