Fix MySQL database character set instruction (#17603)
The currently instructed character set `utf8mb4 COLLATE utf8mb4_unicode_ci;` does not work on mysql 8. 
When I do: `airflow db init` the following error occurs:
`
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 3072 bytes')
`
Changing to this character set: `utf8 COLLATE utf8_general_ci;` solved the problem